/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.AutopiaOptionsProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.AutopiaOptionsProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.AutopiaOptionsProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.AutopiaOptionsProto.displayName = 'proto.keyhole.dbroot.AutopiaOptionsProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.AutopiaOptionsProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.AutopiaOptionsProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadataServerUrl: jspb.Message.getFieldWithDefault(msg, 1, "http://cbk0.google.com/cbk"),
    depthmapServerUrl: jspb.Message.getFieldWithDefault(msg, 2, "http://cbk0.google.com/cbk"),
    coverageOverlayUrl: jspb.Message.getField(msg, 3),
    maxImageryQps: jspb.Message.getOptionalFloatingPointField(msg, 4),
    maxMetadataDepthmapQps: jspb.Message.getOptionalFloatingPointField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.AutopiaOptionsProto}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.AutopiaOptionsProto;
  return proto.keyhole.dbroot.AutopiaOptionsProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.AutopiaOptionsProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.AutopiaOptionsProto}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMetadataServerUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDepthmapServerUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCoverageOverlayUrl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaxImageryQps(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMaxMetadataDepthmapQps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.AutopiaOptionsProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.AutopiaOptionsProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.AutopiaOptionsProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeFloat(
      5,
      f
    );
  }
};


/**
 * optional string metadata_server_url = 1;
 * @return {string}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.getMetadataServerUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, "http://cbk0.google.com/cbk"));
};


/** @param {string} value */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.setMetadataServerUrl = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.AutopiaOptionsProto.prototype.clearMetadataServerUrl = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.hasMetadataServerUrl = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string depthmap_server_url = 2;
 * @return {string}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.getDepthmapServerUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, "http://cbk0.google.com/cbk"));
};


/** @param {string} value */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.setDepthmapServerUrl = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.dbroot.AutopiaOptionsProto.prototype.clearDepthmapServerUrl = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.hasDepthmapServerUrl = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string coverage_overlay_url = 3;
 * @return {string}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.getCoverageOverlayUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.setCoverageOverlayUrl = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.keyhole.dbroot.AutopiaOptionsProto.prototype.clearCoverageOverlayUrl = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.hasCoverageOverlayUrl = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional float max_imagery_qps = 4;
 * @return {number}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.getMaxImageryQps = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.setMaxImageryQps = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.keyhole.dbroot.AutopiaOptionsProto.prototype.clearMaxImageryQps = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.hasMaxImageryQps = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional float max_metadata_depthmap_qps = 5;
 * @return {number}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.getMaxMetadataDepthmapQps = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.setMaxMetadataDepthmapQps = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.keyhole.dbroot.AutopiaOptionsProto.prototype.clearMaxMetadataDepthmapQps = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.AutopiaOptionsProto.prototype.hasMaxMetadataDepthmapQps = function() {
  return jspb.Message.getField(this, 5) != null;
};


