/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.DbRootRefProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.keyhole.dbroot.RequirementProto');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.DbRootRefProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.DbRootRefProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.DbRootRefProto.displayName = 'proto.keyhole.dbroot.DbRootRefProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.DbRootRefProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.DbRootRefProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.DbRootRefProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getField(msg, 2),
    isCritical: jspb.Message.getFieldWithDefault(msg, 1, false),
    requirements: (f = msg.getRequirements()) && proto.keyhole.dbroot.RequirementProto.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.DbRootRefProto}
 */
proto.keyhole.dbroot.DbRootRefProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.DbRootRefProto;
  return proto.keyhole.dbroot.DbRootRefProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.DbRootRefProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.DbRootRefProto}
 */
proto.keyhole.dbroot.DbRootRefProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsCritical(value);
      break;
    case 3:
      var value = new proto.keyhole.dbroot.RequirementProto;
      reader.readMessage(value,proto.keyhole.dbroot.RequirementProto.deserializeBinaryFromReader);
      msg.setRequirements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.DbRootRefProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.DbRootRefProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.DbRootRefProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getRequirements();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.keyhole.dbroot.RequirementProto.serializeBinaryToWriter
    );
  }
};


/**
 * required string url = 2;
 * @return {string}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.keyhole.dbroot.DbRootRefProto.prototype.setUrl = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.dbroot.DbRootRefProto.prototype.clearUrl = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool is_critical = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.getIsCritical = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.keyhole.dbroot.DbRootRefProto.prototype.setIsCritical = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.DbRootRefProto.prototype.clearIsCritical = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.hasIsCritical = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RequirementProto requirements = 3;
 * @return {?proto.keyhole.dbroot.RequirementProto}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.getRequirements = function() {
  return /** @type{?proto.keyhole.dbroot.RequirementProto} */ (
    jspb.Message.getWrapperField(this, proto.keyhole.dbroot.RequirementProto, 3));
};


/** @param {?proto.keyhole.dbroot.RequirementProto|undefined} value */
proto.keyhole.dbroot.DbRootRefProto.prototype.setRequirements = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.keyhole.dbroot.DbRootRefProto.prototype.clearRequirements = function() {
  this.setRequirements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.DbRootRefProto.prototype.hasRequirements = function() {
  return jspb.Message.getField(this, 3) != null;
};


