/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.DrawFlagProto');
goog.provide('proto.keyhole.dbroot.DrawFlagProto.DrawFlagType');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.DrawFlagProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.DrawFlagProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.DrawFlagProto.displayName = 'proto.keyhole.dbroot.DrawFlagProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.DrawFlagProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.DrawFlagProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.DrawFlagProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.DrawFlagProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    drawFlagType: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.DrawFlagProto}
 */
proto.keyhole.dbroot.DrawFlagProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.DrawFlagProto;
  return proto.keyhole.dbroot.DrawFlagProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.DrawFlagProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.DrawFlagProto}
 */
proto.keyhole.dbroot.DrawFlagProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.keyhole.dbroot.DrawFlagProto.DrawFlagType} */ (reader.readEnum());
      msg.setDrawFlagType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.DrawFlagProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.DrawFlagProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.DrawFlagProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.DrawFlagProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.keyhole.dbroot.DrawFlagProto.DrawFlagType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.keyhole.dbroot.DrawFlagProto.DrawFlagType = {
  TYPE_FILL_ONLY: 1,
  TYPE_OUTLINE_ONLY: 2,
  TYPE_FILL_AND_OUTLINE: 3,
  TYPE_ANTIALIASING: 4,
  TYPE_CENTER_LABEL: 5
};

/**
 * required DrawFlagType draw_flag_type = 1;
 * @return {!proto.keyhole.dbroot.DrawFlagProto.DrawFlagType}
 */
proto.keyhole.dbroot.DrawFlagProto.prototype.getDrawFlagType = function() {
  return /** @type {!proto.keyhole.dbroot.DrawFlagProto.DrawFlagType} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/** @param {!proto.keyhole.dbroot.DrawFlagProto.DrawFlagType} value */
proto.keyhole.dbroot.DrawFlagProto.prototype.setDrawFlagType = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.DrawFlagProto.prototype.clearDrawFlagType = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.DrawFlagProto.prototype.hasDrawFlagType = function() {
  return jspb.Message.getField(this, 1) != null;
};


