/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.EncryptedDbRootProto');
goog.provide('proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.EncryptedDbRootProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.EncryptedDbRootProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.EncryptedDbRootProto.displayName = 'proto.keyhole.dbroot.EncryptedDbRootProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.EncryptedDbRootProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.EncryptedDbRootProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    encryptionType: jspb.Message.getField(msg, 1),
    encryptionData: msg.getEncryptionData_asB64(),
    dbrootData: msg.getDbrootData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.EncryptedDbRootProto}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.EncryptedDbRootProto;
  return proto.keyhole.dbroot.EncryptedDbRootProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.EncryptedDbRootProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.EncryptedDbRootProto}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType} */ (reader.readEnum());
      msg.setEncryptionType(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptionData(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setDbrootData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.EncryptedDbRootProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.EncryptedDbRootProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.EncryptedDbRootProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType = {
  ENCRYPTION_XOR: 0
};

/**
 * optional EncryptionType encryption_type = 1;
 * @return {!proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getEncryptionType = function() {
  return /** @type {!proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.keyhole.dbroot.EncryptedDbRootProto.EncryptionType} value */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.setEncryptionType = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.EncryptedDbRootProto.prototype.clearEncryptionType = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.hasEncryptionType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes encryption_data = 2;
 * @return {string}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getEncryptionData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes encryption_data = 2;
 * This is a type-conversion wrapper around `getEncryptionData()`
 * @return {string}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getEncryptionData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptionData()));
};


/**
 * optional bytes encryption_data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptionData()`
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getEncryptionData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptionData()));
};


/** @param {!(string|Uint8Array)} value */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.setEncryptionData = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.dbroot.EncryptedDbRootProto.prototype.clearEncryptionData = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.hasEncryptionData = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes dbroot_data = 3;
 * @return {string}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getDbrootData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes dbroot_data = 3;
 * This is a type-conversion wrapper around `getDbrootData()`
 * @return {string}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getDbrootData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getDbrootData()));
};


/**
 * optional bytes dbroot_data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getDbrootData()`
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.getDbrootData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getDbrootData()));
};


/** @param {!(string|Uint8Array)} value */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.setDbrootData = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.keyhole.dbroot.EncryptedDbRootProto.prototype.clearDbrootData = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.EncryptedDbRootProto.prototype.hasDbrootData = function() {
  return jspb.Message.getField(this, 3) != null;
};


