/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.LayerProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.keyhole.dbroot.ZoomRangeProto');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.LayerProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.keyhole.dbroot.LayerProto.repeatedFields_, null);
};
goog.inherits(proto.keyhole.dbroot.LayerProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.LayerProto.displayName = 'proto.keyhole.dbroot.LayerProto';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.keyhole.dbroot.LayerProto.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.LayerProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.LayerProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.LayerProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.LayerProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    zoomRangeList: jspb.Message.toObjectList(msg.getZoomRangeList(),
    proto.keyhole.dbroot.ZoomRangeProto.toObject, includeInstance),
    preserveTextLevel: jspb.Message.getFieldWithDefault(msg, 2, 30),
    lodBeginTransition: jspb.Message.getField(msg, 4),
    lodEndTransition: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.LayerProto}
 */
proto.keyhole.dbroot.LayerProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.LayerProto;
  return proto.keyhole.dbroot.LayerProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.LayerProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.LayerProto}
 */
proto.keyhole.dbroot.LayerProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.keyhole.dbroot.ZoomRangeProto;
      reader.readMessage(value,proto.keyhole.dbroot.ZoomRangeProto.deserializeBinaryFromReader);
      msg.addZoomRange(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPreserveTextLevel(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLodBeginTransition(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLodEndTransition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.LayerProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.LayerProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.LayerProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.LayerProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getZoomRangeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.keyhole.dbroot.ZoomRangeProto.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * repeated ZoomRangeProto zoom_range = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.keyhole.dbroot.ZoomRangeProto>}
 */
proto.keyhole.dbroot.LayerProto.prototype.getZoomRangeList = function() {
  return /** @type{!Array.<!proto.keyhole.dbroot.ZoomRangeProto>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.keyhole.dbroot.ZoomRangeProto, 1));
};


/** @param {!Array.<!proto.keyhole.dbroot.ZoomRangeProto>} value */
proto.keyhole.dbroot.LayerProto.prototype.setZoomRangeList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.keyhole.dbroot.ZoomRangeProto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.keyhole.dbroot.ZoomRangeProto}
 */
proto.keyhole.dbroot.LayerProto.prototype.addZoomRange = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.keyhole.dbroot.ZoomRangeProto, opt_index);
};


proto.keyhole.dbroot.LayerProto.prototype.clearZoomRangeList = function() {
  this.setZoomRangeList([]);
};


/**
 * optional int32 preserve_text_level = 2;
 * @return {number}
 */
proto.keyhole.dbroot.LayerProto.prototype.getPreserveTextLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 30));
};


/** @param {number} value */
proto.keyhole.dbroot.LayerProto.prototype.setPreserveTextLevel = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.dbroot.LayerProto.prototype.clearPreserveTextLevel = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.LayerProto.prototype.hasPreserveTextLevel = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool lod_begin_transition = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.keyhole.dbroot.LayerProto.prototype.getLodBeginTransition = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.keyhole.dbroot.LayerProto.prototype.setLodBeginTransition = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.keyhole.dbroot.LayerProto.prototype.clearLodBeginTransition = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.LayerProto.prototype.hasLodBeginTransition = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool lod_end_transition = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.keyhole.dbroot.LayerProto.prototype.getLodEndTransition = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.keyhole.dbroot.LayerProto.prototype.setLodEndTransition = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.keyhole.dbroot.LayerProto.prototype.clearLodEndTransition = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.LayerProto.prototype.hasLodEndTransition = function() {
  return jspb.Message.getField(this, 5) != null;
};


