/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.PlanetModelProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.PlanetModelProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.PlanetModelProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.PlanetModelProto.displayName = 'proto.keyhole.dbroot.PlanetModelProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.PlanetModelProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.PlanetModelProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.PlanetModelProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    radius: +jspb.Message.getFieldWithDefault(msg, 1, 6378.137),
    flattening: +jspb.Message.getFieldWithDefault(msg, 2, 0.00335281066474748),
    elevationBias: jspb.Message.getOptionalFloatingPointField(msg, 4),
    negativeAltitudeExponentBias: jspb.Message.getField(msg, 5),
    compressedNegativeAltitudeThreshold: jspb.Message.getOptionalFloatingPointField(msg, 6)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.PlanetModelProto}
 */
proto.keyhole.dbroot.PlanetModelProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.PlanetModelProto;
  return proto.keyhole.dbroot.PlanetModelProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.PlanetModelProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.PlanetModelProto}
 */
proto.keyhole.dbroot.PlanetModelProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRadius(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setFlattening(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setElevationBias(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNegativeAltitudeExponentBias(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCompressedNegativeAltitudeThreshold(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.PlanetModelProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.PlanetModelProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.PlanetModelProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
};


/**
 * optional double radius = 1;
 * @return {number}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.getRadius = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 6378.137));
};


/** @param {number} value */
proto.keyhole.dbroot.PlanetModelProto.prototype.setRadius = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.PlanetModelProto.prototype.clearRadius = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.hasRadius = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double flattening = 2;
 * @return {number}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.getFlattening = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.00335281066474748));
};


/** @param {number} value */
proto.keyhole.dbroot.PlanetModelProto.prototype.setFlattening = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.dbroot.PlanetModelProto.prototype.clearFlattening = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.hasFlattening = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double elevation_bias = 4;
 * @return {number}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.getElevationBias = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.keyhole.dbroot.PlanetModelProto.prototype.setElevationBias = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.keyhole.dbroot.PlanetModelProto.prototype.clearElevationBias = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.hasElevationBias = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 negative_altitude_exponent_bias = 5;
 * @return {number}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.getNegativeAltitudeExponentBias = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.keyhole.dbroot.PlanetModelProto.prototype.setNegativeAltitudeExponentBias = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.keyhole.dbroot.PlanetModelProto.prototype.clearNegativeAltitudeExponentBias = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.hasNegativeAltitudeExponentBias = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double compressed_negative_altitude_threshold = 6;
 * @return {number}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.getCompressedNegativeAltitudeThreshold = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.keyhole.dbroot.PlanetModelProto.prototype.setCompressedNegativeAltitudeThreshold = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.keyhole.dbroot.PlanetModelProto.prototype.clearCompressedNegativeAltitudeThreshold = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetModelProto.prototype.hasCompressedNegativeAltitudeThreshold = function() {
  return jspb.Message.getField(this, 6) != null;
};


