/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.PlanetaryDatabaseProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.keyhole.dbroot.StringIdOrValueProto');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.PlanetaryDatabaseProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.PlanetaryDatabaseProto.displayName = 'proto.keyhole.dbroot.PlanetaryDatabaseProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.PlanetaryDatabaseProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.PlanetaryDatabaseProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: (f = msg.getUrl()) && proto.keyhole.dbroot.StringIdOrValueProto.toObject(includeInstance, f),
    name: (f = msg.getName()) && proto.keyhole.dbroot.StringIdOrValueProto.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.PlanetaryDatabaseProto}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.PlanetaryDatabaseProto;
  return proto.keyhole.dbroot.PlanetaryDatabaseProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.PlanetaryDatabaseProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.PlanetaryDatabaseProto}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.keyhole.dbroot.StringIdOrValueProto;
      reader.readMessage(value,proto.keyhole.dbroot.StringIdOrValueProto.deserializeBinaryFromReader);
      msg.setUrl(value);
      break;
    case 2:
      var value = new proto.keyhole.dbroot.StringIdOrValueProto;
      reader.readMessage(value,proto.keyhole.dbroot.StringIdOrValueProto.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.PlanetaryDatabaseProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.PlanetaryDatabaseProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.keyhole.dbroot.StringIdOrValueProto.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.keyhole.dbroot.StringIdOrValueProto.serializeBinaryToWriter
    );
  }
};


/**
 * required StringIdOrValueProto url = 1;
 * @return {!proto.keyhole.dbroot.StringIdOrValueProto}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.getUrl = function() {
  return /** @type{!proto.keyhole.dbroot.StringIdOrValueProto} */ (
    jspb.Message.getWrapperField(this, proto.keyhole.dbroot.StringIdOrValueProto, 1, 1));
};


/** @param {!proto.keyhole.dbroot.StringIdOrValueProto} value */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.setUrl = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.clearUrl = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required StringIdOrValueProto name = 2;
 * @return {!proto.keyhole.dbroot.StringIdOrValueProto}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.getName = function() {
  return /** @type{!proto.keyhole.dbroot.StringIdOrValueProto} */ (
    jspb.Message.getWrapperField(this, proto.keyhole.dbroot.StringIdOrValueProto, 2, 1));
};


/** @param {!proto.keyhole.dbroot.StringIdOrValueProto} value */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.setName = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.clearName = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.PlanetaryDatabaseProto.prototype.hasName = function() {
  return jspb.Message.getField(this, 2) != null;
};


