/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.StyleMapProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.StyleMapProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.keyhole.dbroot.StyleMapProto.repeatedFields_, null);
};
goog.inherits(proto.keyhole.dbroot.StyleMapProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.StyleMapProto.displayName = 'proto.keyhole.dbroot.StyleMapProto';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.keyhole.dbroot.StyleMapProto.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.StyleMapProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.StyleMapProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.StyleMapProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    styleMapId: jspb.Message.getField(msg, 1),
    channelIdList: jspb.Message.getField(msg, 2),
    normalStyleAttribute: jspb.Message.getField(msg, 3),
    highlightStyleAttribute: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.StyleMapProto}
 */
proto.keyhole.dbroot.StyleMapProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.StyleMapProto;
  return proto.keyhole.dbroot.StyleMapProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.StyleMapProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.StyleMapProto}
 */
proto.keyhole.dbroot.StyleMapProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStyleMapId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.addChannelId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNormalStyleAttribute(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHighlightStyleAttribute(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.StyleMapProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.StyleMapProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.StyleMapProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getChannelIdList();
  if (f.length > 0) {
    writer.writeRepeatedInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * required int32 style_map_id = 1;
 * @return {number}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.getStyleMapId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.keyhole.dbroot.StyleMapProto.prototype.setStyleMapId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.StyleMapProto.prototype.clearStyleMapId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.hasStyleMapId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated int32 channel_id = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.getChannelIdList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 2));
};


/** @param {!Array.<number>} value */
proto.keyhole.dbroot.StyleMapProto.prototype.setChannelIdList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.keyhole.dbroot.StyleMapProto.prototype.addChannelId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.keyhole.dbroot.StyleMapProto.prototype.clearChannelIdList = function() {
  this.setChannelIdList([]);
};


/**
 * optional int32 normal_style_attribute = 3;
 * @return {number}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.getNormalStyleAttribute = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.keyhole.dbroot.StyleMapProto.prototype.setNormalStyleAttribute = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.keyhole.dbroot.StyleMapProto.prototype.clearNormalStyleAttribute = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.hasNormalStyleAttribute = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 highlight_style_attribute = 4;
 * @return {number}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.getHighlightStyleAttribute = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.keyhole.dbroot.StyleMapProto.prototype.setHighlightStyleAttribute = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.keyhole.dbroot.StyleMapProto.prototype.clearHighlightStyleAttribute = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.StyleMapProto.prototype.hasHighlightStyleAttribute = function() {
  return jspb.Message.getField(this, 4) != null;
};


