/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.dbroot.TimeMachineOptionsProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.dbroot.TimeMachineOptionsProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.dbroot.TimeMachineOptionsProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.dbroot.TimeMachineOptionsProto.displayName = 'proto.keyhole.dbroot.TimeMachineOptionsProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.dbroot.TimeMachineOptionsProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.dbroot.TimeMachineOptionsProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverUrl: jspb.Message.getField(msg, 1),
    isTimemachine: jspb.Message.getField(msg, 2),
    dwellTimeMs: jspb.Message.getFieldWithDefault(msg, 3, 500),
    discoverabilityAltitudeMeters: jspb.Message.getFieldWithDefault(msg, 4, 15000)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.dbroot.TimeMachineOptionsProto}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.dbroot.TimeMachineOptionsProto;
  return proto.keyhole.dbroot.TimeMachineOptionsProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.dbroot.TimeMachineOptionsProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.dbroot.TimeMachineOptionsProto}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerUrl(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsTimemachine(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDwellTimeMs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDiscoverabilityAltitudeMeters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.dbroot.TimeMachineOptionsProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.dbroot.TimeMachineOptionsProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string server_url = 1;
 * @return {string}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.getServerUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.setServerUrl = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.clearServerUrl = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.hasServerUrl = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool is_timemachine = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.getIsTimemachine = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.setIsTimemachine = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.clearIsTimemachine = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.hasIsTimemachine = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 dwell_time_ms = 3;
 * @return {number}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.getDwellTimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 500));
};


/** @param {number} value */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.setDwellTimeMs = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.clearDwellTimeMs = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.hasDwellTimeMs = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 discoverability_altitude_meters = 4;
 * @return {number}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.getDiscoverabilityAltitudeMeters = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 15000));
};


/** @param {number} value */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.setDiscoverabilityAltitudeMeters = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.clearDiscoverabilityAltitudeMeters = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.dbroot.TimeMachineOptionsProto.prototype.hasDiscoverabilityAltitudeMeters = function() {
  return jspb.Message.getField(this, 4) != null;
};


