/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.geo_globetrotter_proto_rocktree.NodeKey');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.displayName = 'proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodeKey: (f = msg.getNodeKey()) && proto.geo_globetrotter_proto_rocktree.NodeKey.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest;
  return proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.geo_globetrotter_proto_rocktree.NodeKey;
      reader.readMessage(value,proto.geo_globetrotter_proto_rocktree.NodeKey.deserializeBinaryFromReader);
      msg.setNodeKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.geo_globetrotter_proto_rocktree.NodeKey.serializeBinaryToWriter
    );
  }
};


/**
 * optional NodeKey node_key = 1;
 * @return {?proto.geo_globetrotter_proto_rocktree.NodeKey}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.prototype.getNodeKey = function() {
  return /** @type{?proto.geo_globetrotter_proto_rocktree.NodeKey} */ (
    jspb.Message.getWrapperField(this, proto.geo_globetrotter_proto_rocktree.NodeKey, 1));
};


/** @param {?proto.geo_globetrotter_proto_rocktree.NodeKey|undefined} value */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.prototype.setNodeKey = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.prototype.clearNodeKey = function() {
  this.setNodeKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.geo_globetrotter_proto_rocktree.BulkMetadataRequest.prototype.hasNodeKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


