/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.geo_globetrotter_proto_rocktree.Copyrights');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.geo_globetrotter_proto_rocktree.Copyright');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.geo_globetrotter_proto_rocktree.Copyrights = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.geo_globetrotter_proto_rocktree.Copyrights.repeatedFields_, null);
};
goog.inherits(proto.geo_globetrotter_proto_rocktree.Copyrights, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.geo_globetrotter_proto_rocktree.Copyrights.displayName = 'proto.geo_globetrotter_proto_rocktree.Copyrights';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.prototype.toObject = function(opt_includeInstance) {
  return proto.geo_globetrotter_proto_rocktree.Copyrights.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.geo_globetrotter_proto_rocktree.Copyrights} msg The msg instance to transform.
 * @return {!Object}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.toObject = function(includeInstance, msg) {
  var f, obj = {
    copyrightsList: jspb.Message.toObjectList(msg.getCopyrightsList(),
    proto.geo_globetrotter_proto_rocktree.Copyright.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.geo_globetrotter_proto_rocktree.Copyrights}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.geo_globetrotter_proto_rocktree.Copyrights;
  return proto.geo_globetrotter_proto_rocktree.Copyrights.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.geo_globetrotter_proto_rocktree.Copyrights} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.geo_globetrotter_proto_rocktree.Copyrights}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.geo_globetrotter_proto_rocktree.Copyright;
      reader.readMessage(value,proto.geo_globetrotter_proto_rocktree.Copyright.deserializeBinaryFromReader);
      msg.addCopyrights(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.geo_globetrotter_proto_rocktree.Copyrights.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.geo_globetrotter_proto_rocktree.Copyrights} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCopyrightsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.geo_globetrotter_proto_rocktree.Copyright.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Copyright copyrights = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.geo_globetrotter_proto_rocktree.Copyright>}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.prototype.getCopyrightsList = function() {
  return /** @type{!Array.<!proto.geo_globetrotter_proto_rocktree.Copyright>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.geo_globetrotter_proto_rocktree.Copyright, 1));
};


/** @param {!Array.<!proto.geo_globetrotter_proto_rocktree.Copyright>} value */
proto.geo_globetrotter_proto_rocktree.Copyrights.prototype.setCopyrightsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.geo_globetrotter_proto_rocktree.Copyright=} opt_value
 * @param {number=} opt_index
 * @return {!proto.geo_globetrotter_proto_rocktree.Copyright}
 */
proto.geo_globetrotter_proto_rocktree.Copyrights.prototype.addCopyrights = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.geo_globetrotter_proto_rocktree.Copyright, opt_index);
};


proto.geo_globetrotter_proto_rocktree.Copyrights.prototype.clearCopyrightsList = function() {
  this.setCopyrightsList([]);
};


