/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.geo_globetrotter_proto_rocktree.TextureData');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.geo_globetrotter_proto_rocktree.NodeKey');
goog.require('proto.geo_globetrotter_proto_rocktree.Texture');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.geo_globetrotter_proto_rocktree.TextureData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.geo_globetrotter_proto_rocktree.TextureData.repeatedFields_, null);
};
goog.inherits(proto.geo_globetrotter_proto_rocktree.TextureData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.geo_globetrotter_proto_rocktree.TextureData.displayName = 'proto.geo_globetrotter_proto_rocktree.TextureData';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.geo_globetrotter_proto_rocktree.TextureData.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.toObject = function(opt_includeInstance) {
  return proto.geo_globetrotter_proto_rocktree.TextureData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.geo_globetrotter_proto_rocktree.TextureData} msg The msg instance to transform.
 * @return {!Object}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodeKey: (f = msg.getNodeKey()) && proto.geo_globetrotter_proto_rocktree.NodeKey.toObject(includeInstance, f),
    texturesList: jspb.Message.toObjectList(msg.getTexturesList(),
    proto.geo_globetrotter_proto_rocktree.Texture.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.geo_globetrotter_proto_rocktree.TextureData}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.geo_globetrotter_proto_rocktree.TextureData;
  return proto.geo_globetrotter_proto_rocktree.TextureData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.geo_globetrotter_proto_rocktree.TextureData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.geo_globetrotter_proto_rocktree.TextureData}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.geo_globetrotter_proto_rocktree.NodeKey;
      reader.readMessage(value,proto.geo_globetrotter_proto_rocktree.NodeKey.deserializeBinaryFromReader);
      msg.setNodeKey(value);
      break;
    case 2:
      var value = new proto.geo_globetrotter_proto_rocktree.Texture;
      reader.readMessage(value,proto.geo_globetrotter_proto_rocktree.Texture.deserializeBinaryFromReader);
      msg.addTextures(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.geo_globetrotter_proto_rocktree.TextureData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.geo_globetrotter_proto_rocktree.TextureData} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.geo_globetrotter_proto_rocktree.TextureData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.geo_globetrotter_proto_rocktree.NodeKey.serializeBinaryToWriter
    );
  }
  f = message.getTexturesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.geo_globetrotter_proto_rocktree.Texture.serializeBinaryToWriter
    );
  }
};


/**
 * optional NodeKey node_key = 1;
 * @return {?proto.geo_globetrotter_proto_rocktree.NodeKey}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.getNodeKey = function() {
  return /** @type{?proto.geo_globetrotter_proto_rocktree.NodeKey} */ (
    jspb.Message.getWrapperField(this, proto.geo_globetrotter_proto_rocktree.NodeKey, 1));
};


/** @param {?proto.geo_globetrotter_proto_rocktree.NodeKey|undefined} value */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.setNodeKey = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.geo_globetrotter_proto_rocktree.TextureData.prototype.clearNodeKey = function() {
  this.setNodeKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.hasNodeKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Texture textures = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.geo_globetrotter_proto_rocktree.Texture>}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.getTexturesList = function() {
  return /** @type{!Array.<!proto.geo_globetrotter_proto_rocktree.Texture>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.geo_globetrotter_proto_rocktree.Texture, 2));
};


/** @param {!Array.<!proto.geo_globetrotter_proto_rocktree.Texture>} value */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.setTexturesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.geo_globetrotter_proto_rocktree.Texture=} opt_value
 * @param {number=} opt_index
 * @return {!proto.geo_globetrotter_proto_rocktree.Texture}
 */
proto.geo_globetrotter_proto_rocktree.TextureData.prototype.addTextures = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.geo_globetrotter_proto_rocktree.Texture, opt_index);
};


proto.geo_globetrotter_proto_rocktree.TextureData.prototype.clearTexturesList = function() {
  this.setTexturesList([]);
};


