/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.TerrainPacketExtraDataProto');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.keyhole.WaterSurfaceTileProto');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.TerrainPacketExtraDataProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.keyhole.TerrainPacketExtraDataProto.repeatedFields_, null);
};
goog.inherits(proto.keyhole.TerrainPacketExtraDataProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.TerrainPacketExtraDataProto.displayName = 'proto.keyhole.TerrainPacketExtraDataProto';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.keyhole.TerrainPacketExtraDataProto.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.TerrainPacketExtraDataProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.TerrainPacketExtraDataProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.TerrainPacketExtraDataProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    waterTileQuadsList: jspb.Message.toObjectList(msg.getWaterTileQuadsList(),
    proto.keyhole.WaterSurfaceTileProto.toObject, includeInstance),
    originalTerrainPacket: msg.getOriginalTerrainPacket_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.TerrainPacketExtraDataProto}
 */
proto.keyhole.TerrainPacketExtraDataProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.TerrainPacketExtraDataProto;
  return proto.keyhole.TerrainPacketExtraDataProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.TerrainPacketExtraDataProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.TerrainPacketExtraDataProto}
 */
proto.keyhole.TerrainPacketExtraDataProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.keyhole.WaterSurfaceTileProto;
      reader.readMessage(value,proto.keyhole.WaterSurfaceTileProto.deserializeBinaryFromReader);
      msg.addWaterTileQuads(value);
      break;
    case 100:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOriginalTerrainPacket(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.TerrainPacketExtraDataProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.TerrainPacketExtraDataProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.TerrainPacketExtraDataProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWaterTileQuadsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.keyhole.WaterSurfaceTileProto.serializeBinaryToWriter
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 100));
  if (f != null) {
    writer.writeBytes(
      100,
      f
    );
  }
};


/**
 * repeated WaterSurfaceTileProto water_tile_quads = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.keyhole.WaterSurfaceTileProto>}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.getWaterTileQuadsList = function() {
  return /** @type{!Array.<!proto.keyhole.WaterSurfaceTileProto>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.keyhole.WaterSurfaceTileProto, 1));
};


/** @param {!Array.<!proto.keyhole.WaterSurfaceTileProto>} value */
proto.keyhole.TerrainPacketExtraDataProto.prototype.setWaterTileQuadsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.keyhole.WaterSurfaceTileProto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.keyhole.WaterSurfaceTileProto}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.addWaterTileQuads = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.keyhole.WaterSurfaceTileProto, opt_index);
};


proto.keyhole.TerrainPacketExtraDataProto.prototype.clearWaterTileQuadsList = function() {
  this.setWaterTileQuadsList([]);
};


/**
 * optional bytes original_terrain_packet = 100;
 * @return {string}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.getOriginalTerrainPacket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 100, ""));
};


/**
 * optional bytes original_terrain_packet = 100;
 * This is a type-conversion wrapper around `getOriginalTerrainPacket()`
 * @return {string}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.getOriginalTerrainPacket_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOriginalTerrainPacket()));
};


/**
 * optional bytes original_terrain_packet = 100;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOriginalTerrainPacket()`
 * @return {!Uint8Array}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.getOriginalTerrainPacket_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOriginalTerrainPacket()));
};


/** @param {!(string|Uint8Array)} value */
proto.keyhole.TerrainPacketExtraDataProto.prototype.setOriginalTerrainPacket = function(value) {
  jspb.Message.setField(this, 100, value);
};


proto.keyhole.TerrainPacketExtraDataProto.prototype.clearOriginalTerrainPacket = function() {
  jspb.Message.setField(this, 100, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.TerrainPacketExtraDataProto.prototype.hasOriginalTerrainPacket = function() {
  return jspb.Message.getField(this, 100) != null;
};


