/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.QuadtreeImageryDates');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.keyhole.QuadtreeImageryDatedTile');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.QuadtreeImageryDates = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.keyhole.QuadtreeImageryDates.repeatedFields_, null);
};
goog.inherits(proto.keyhole.QuadtreeImageryDates, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.QuadtreeImageryDates.displayName = 'proto.keyhole.QuadtreeImageryDates';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.keyhole.QuadtreeImageryDates.repeatedFields_ = [1,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.QuadtreeImageryDates.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.QuadtreeImageryDates.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.QuadtreeImageryDates} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.QuadtreeImageryDates.toObject = function(includeInstance, msg) {
  var f, obj = {
    datedTileList: jspb.Message.toObjectList(msg.getDatedTileList(),
    proto.keyhole.QuadtreeImageryDatedTile.toObject, includeInstance),
    sharedTileDate: jspb.Message.getField(msg, 2),
    coarseTileDatesList: jspb.Message.getField(msg, 3),
    sharedTileMilliseconds: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.QuadtreeImageryDates}
 */
proto.keyhole.QuadtreeImageryDates.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.QuadtreeImageryDates;
  return proto.keyhole.QuadtreeImageryDates.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.QuadtreeImageryDates} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.QuadtreeImageryDates}
 */
proto.keyhole.QuadtreeImageryDates.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.keyhole.QuadtreeImageryDatedTile;
      reader.readMessage(value,proto.keyhole.QuadtreeImageryDatedTile.deserializeBinaryFromReader);
      msg.addDatedTile(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSharedTileDate(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.addCoarseTileDates(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSharedTileMilliseconds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.QuadtreeImageryDates.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.QuadtreeImageryDates.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.QuadtreeImageryDates} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.QuadtreeImageryDates.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatedTileList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.keyhole.QuadtreeImageryDatedTile.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCoarseTileDatesList();
  if (f.length > 0) {
    writer.writeRepeatedInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * repeated QuadtreeImageryDatedTile dated_tile = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.keyhole.QuadtreeImageryDatedTile>}
 */
proto.keyhole.QuadtreeImageryDates.prototype.getDatedTileList = function() {
  return /** @type{!Array.<!proto.keyhole.QuadtreeImageryDatedTile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.keyhole.QuadtreeImageryDatedTile, 1));
};


/** @param {!Array.<!proto.keyhole.QuadtreeImageryDatedTile>} value */
proto.keyhole.QuadtreeImageryDates.prototype.setDatedTileList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.keyhole.QuadtreeImageryDatedTile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.keyhole.QuadtreeImageryDatedTile}
 */
proto.keyhole.QuadtreeImageryDates.prototype.addDatedTile = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.keyhole.QuadtreeImageryDatedTile, opt_index);
};


proto.keyhole.QuadtreeImageryDates.prototype.clearDatedTileList = function() {
  this.setDatedTileList([]);
};


/**
 * optional int32 shared_tile_date = 2;
 * @return {number}
 */
proto.keyhole.QuadtreeImageryDates.prototype.getSharedTileDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.keyhole.QuadtreeImageryDates.prototype.setSharedTileDate = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.QuadtreeImageryDates.prototype.clearSharedTileDate = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.QuadtreeImageryDates.prototype.hasSharedTileDate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated int32 coarse_tile_dates = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.keyhole.QuadtreeImageryDates.prototype.getCoarseTileDatesList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 3));
};


/** @param {!Array.<number>} value */
proto.keyhole.QuadtreeImageryDates.prototype.setCoarseTileDatesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.keyhole.QuadtreeImageryDates.prototype.addCoarseTileDates = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.keyhole.QuadtreeImageryDates.prototype.clearCoarseTileDatesList = function() {
  this.setCoarseTileDatesList([]);
};


/**
 * optional int32 shared_tile_milliseconds = 4;
 * @return {number}
 */
proto.keyhole.QuadtreeImageryDates.prototype.getSharedTileMilliseconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.keyhole.QuadtreeImageryDates.prototype.setSharedTileMilliseconds = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.keyhole.QuadtreeImageryDates.prototype.clearSharedTileMilliseconds = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.QuadtreeImageryDates.prototype.hasSharedTileMilliseconds = function() {
  return jspb.Message.getField(this, 4) != null;
};


