/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.QuadtreeImageryDatedTile');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.keyhole.QuadtreeImageryTimedTile');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.QuadtreeImageryDatedTile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.keyhole.QuadtreeImageryDatedTile.repeatedFields_, null);
};
goog.inherits(proto.keyhole.QuadtreeImageryDatedTile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.QuadtreeImageryDatedTile.displayName = 'proto.keyhole.QuadtreeImageryDatedTile';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.keyhole.QuadtreeImageryDatedTile.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.QuadtreeImageryDatedTile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.QuadtreeImageryDatedTile} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.QuadtreeImageryDatedTile.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: jspb.Message.getField(msg, 1),
    datedTileEpoch: jspb.Message.getField(msg, 2),
    provider: jspb.Message.getField(msg, 3),
    timedTilesList: jspb.Message.toObjectList(msg.getTimedTilesList(),
    proto.keyhole.QuadtreeImageryTimedTile.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.QuadtreeImageryDatedTile}
 */
proto.keyhole.QuadtreeImageryDatedTile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.QuadtreeImageryDatedTile;
  return proto.keyhole.QuadtreeImageryDatedTile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.QuadtreeImageryDatedTile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.QuadtreeImageryDatedTile}
 */
proto.keyhole.QuadtreeImageryDatedTile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDatedTileEpoch(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProvider(value);
      break;
    case 4:
      var value = new proto.keyhole.QuadtreeImageryTimedTile;
      reader.readMessage(value,proto.keyhole.QuadtreeImageryTimedTile.deserializeBinaryFromReader);
      msg.addTimedTiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.QuadtreeImageryDatedTile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.QuadtreeImageryDatedTile} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.QuadtreeImageryDatedTile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTimedTilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.keyhole.QuadtreeImageryTimedTile.serializeBinaryToWriter
    );
  }
};


/**
 * required int32 date = 1;
 * @return {number}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.getDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.keyhole.QuadtreeImageryDatedTile.prototype.setDate = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.QuadtreeImageryDatedTile.prototype.clearDate = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.hasDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 dated_tile_epoch = 2;
 * @return {number}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.getDatedTileEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.keyhole.QuadtreeImageryDatedTile.prototype.setDatedTileEpoch = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.QuadtreeImageryDatedTile.prototype.clearDatedTileEpoch = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.hasDatedTileEpoch = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 provider = 3;
 * @return {number}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.getProvider = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.keyhole.QuadtreeImageryDatedTile.prototype.setProvider = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.keyhole.QuadtreeImageryDatedTile.prototype.clearProvider = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.hasProvider = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated QuadtreeImageryTimedTile timed_tiles = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.keyhole.QuadtreeImageryTimedTile>}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.getTimedTilesList = function() {
  return /** @type{!Array.<!proto.keyhole.QuadtreeImageryTimedTile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.keyhole.QuadtreeImageryTimedTile, 4));
};


/** @param {!Array.<!proto.keyhole.QuadtreeImageryTimedTile>} value */
proto.keyhole.QuadtreeImageryDatedTile.prototype.setTimedTilesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.keyhole.QuadtreeImageryTimedTile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.keyhole.QuadtreeImageryTimedTile}
 */
proto.keyhole.QuadtreeImageryDatedTile.prototype.addTimedTiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.keyhole.QuadtreeImageryTimedTile, opt_index);
};


proto.keyhole.QuadtreeImageryDatedTile.prototype.clearTimedTilesList = function() {
  this.setTimedTilesList([]);
};


