/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.keyhole.replica.ReplicaCollection');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.keyhole.replica.ReplicaCollection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.keyhole.replica.ReplicaCollection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.keyhole.replica.ReplicaCollection.displayName = 'proto.keyhole.replica.ReplicaCollection';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.keyhole.replica.ReplicaCollection.prototype.toObject = function(opt_includeInstance) {
  return proto.keyhole.replica.ReplicaCollection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.keyhole.replica.ReplicaCollection} msg The msg instance to transform.
 * @return {!Object}
 */
proto.keyhole.replica.ReplicaCollection.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getField(msg, 1),
    numModels: jspb.Message.getField(msg, 2),
    numPackets: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.keyhole.replica.ReplicaCollection}
 */
proto.keyhole.replica.ReplicaCollection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.keyhole.replica.ReplicaCollection;
  return proto.keyhole.replica.ReplicaCollection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.keyhole.replica.ReplicaCollection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.keyhole.replica.ReplicaCollection}
 */
proto.keyhole.replica.ReplicaCollection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumModels(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumPackets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.keyhole.replica.ReplicaCollection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.keyhole.replica.ReplicaCollection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.keyhole.replica.ReplicaCollection} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.keyhole.replica.ReplicaCollection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * required string name = 1;
 * @return {string}
 */
proto.keyhole.replica.ReplicaCollection.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.keyhole.replica.ReplicaCollection.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.keyhole.replica.ReplicaCollection.prototype.clearName = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.replica.ReplicaCollection.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 num_models = 2;
 * @return {number}
 */
proto.keyhole.replica.ReplicaCollection.prototype.getNumModels = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.keyhole.replica.ReplicaCollection.prototype.setNumModels = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.keyhole.replica.ReplicaCollection.prototype.clearNumModels = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.replica.ReplicaCollection.prototype.hasNumModels = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 num_packets = 3;
 * @return {number}
 */
proto.keyhole.replica.ReplicaCollection.prototype.getNumPackets = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.keyhole.replica.ReplicaCollection.prototype.setNumPackets = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.keyhole.replica.ReplicaCollection.prototype.clearNumPackets = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.keyhole.replica.ReplicaCollection.prototype.hasNumPackets = function() {
  return jspb.Message.getField(this, 3) != null;
};


